/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [
    // home
    {
      type: 'doc',
      id: 'home'
    },
    // Startup Guide
    {
      type: 'category',
      collapsed: false,
      items : [
        // Startup Guide - installation
        {
          type: 'autogenerated',
          dirName: 'startup-guide'
        },
      ], 
      label: 'Startup Guide' 
    },
    // tutorial
    {
      type: 'category',
      collapsed: false,
      label: 'Tutorial',
      items : [
        {
          type: 'autogenerated',
          dirName: 'tutorials'  
        }
      ]
    },
    // software reference
    {
      type: 'doc',
      id: 'external/software-reference'
    },
    // Appendix
    {
      type: 'category',
      collapsed: false,
      label: 'Appendix',
      items : [
        {
          type: 'doc',
          id: 'cross-reference'
        },
        {
          type: 'autogenerated',
          dirName: 'lessons'  
        },
        {
          type: 'autogenerated',
          dirName: 'external/aravis'
        },
        {
          type: 'autogenerated',
          dirName: 'internal'
        },
        {
          type: 'autogenerated',
          dirName: 'this_version'
        },
      ]
    }

  ],

};

module.exports = sidebars;
